name: Run server tests + deploy to Heroku

env:
      YELP_API_KEY: ${{ secrets.YELP_API_KEY }}
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn Modules
      run: yarn
    - name: Run Jest Tests
      run: yarn test "../__tests__"
  
  build:
    name: Request Netlify Webhook
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hidden-mesa-04199" #Must be unique in Heroku
          heroku_email: "luke.levasseur16@gmail.com"