name: Run server tests

env:
      YELP_API_KEY: ${{ secrets.YELP_API_KEY }}
on: 
  push:
  pull_request:
  workflow_run:
    workflows:
      - deploy
    types:
      - requested

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn Modules
      run: yarn
    - name: Run Jest Tests
      run: yarn test "../__tests__"